api_platform:
  title: Evaluation API
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
    html:
      mime_types: ["text/html"]
    multipart:
      mime_types: ["multipart/form-data"]
